export const responseCodeMap = {
  1: 'Success.',
  2: 'Invalid service: this service does not exist.',
  3: 'Authentication failed: You do not have permissions to access the service.',
  4: "Invalid format: This service doesn't exist in that format.",
  5: 'Invalid parameters: Your request parameters are incorrect.',
  6: 'Invalid id: The pre-requisite id is invalid or not found.',
  7: 'Invalid API key: You must be granted a valid key.',
  8: 'Duplicate entry: The data you tried to submit already exists.',
  9: 'Service offline: This service is temporarily offline, try again later.',
  10: 'Suspended API key: Access to your account has been suspended, contact TMDB.',
  11: 'Internal error: Something went wrong, contact TMDB.',
  12: 'The item/record was updated successfully.',
  13: 'The item/record was deleted successfully.',
  14: 'Authentication failed.',
  15: 'Failed.',
  16: 'Device denied.',
  17: 'Session denied.',
  18: 'Validation failed.',
  19: 'Invalid accept header.',
  20: 'Invalid date range: Should be a range no longer than 14 days.',
  21: 'Entry not found: The item you are trying to edit cannot be found.',
  22: 'Invalid page: Pages start at 1 and max at 1000. They are expected to be an integer.',
  23: 'Invalid date: Format needs to be YYYY-MM-DD.',
  24: 'Your request to the backend server timed out. Try again.',
  25: 'Your request count (#) is over the allowed limit of (40).',
  26: 'You must provide a username and password.',
  27: 'Too many append to response objects: The maximum number of remote calls is 20.',
  28: 'Invalid timezone: Please consult the documentation for a valid timezone.',
  29: 'You must confirm this action: Please provide a confirm=true parameter.',
  30: 'Invalid username and/or password: You did not provide a valid login.',
  31: 'Account disabled: Your account is no longer active. Contact TMDB if this is an error.',
  32: 'Email not verified: Your email address has not been verified.',
  33: 'Invalid request token: The request token is either expired or invalid.',
  34: 'The resource you requested could not be found.',
  35: 'Invalid token.',
  36: "This token hasn't been granted write permission by the user.",
  37: 'The requested session could not be found.',
  38: "You don't have permission to edit this resource.",
  39: 'This resource is private.',
  40: 'Nothing to update.',
  41: "This request token hasn't been approved by the user.",
  42: 'This request method is not supported for this resource.',
  43: "Couldn't connect to the backend server.",
  44: 'The ID is invalid.',
  45: 'This user has been suspended.',
  46: 'The API is undergoing maintenance. Try again later.',
  47: 'The input is not valid.',
}
